// <auto-generated />
using ComicsAndAllProject.Plugins.EFCore.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ComicsAndAllProject.Plugins.EFCore.Migrations
{
    [DbContext(typeof(ComicsAndAllDbContext))]
    [Migration("20260629130500_AddUserProfiles")]
    partial class AddUserProfiles
    {
    }
}
